item.ud-mod-ud-wreckage-alloy.name = Wreckage Alloy
item.ud-mod-ud-wreckage-alloy.description = Pioneer alloy wreckage
item.ud-mod-ud-wreckage-glass.name = Wreckage Glass
item.ud-mod-ud-wreckage-glass.description = Pioneer glass wreckage
item.ud-mod-ud-wreckage-fiber.name = Wreckage Fiber
item.ud-mod-ud-wreckage-fiber.description = Pioneer fiber wreckage
item.ud-mod-ud-root.name = Root
item.ud-mod-ud-root.description = Unknown organic root
item.ud-mod-ud-prec-core-fight.name = Prec-Core: Fight
item.ud-mod-ud-prec-core-fight.description = At least it doesn't bite
item.ud-mod-ud-prec-core-exist.name = Prec-Core: Exist
item.ud-mod-ud-prec-core-exist.description = Why won't it come apart
item.ud-mod-ud-prec-core-migrate.name = Prec-Core: Migrate
item.ud-mod-ud-prec-core-migrate.description = Probe misaligned again
item.ud-mod-ud-prec-core-final.name = Pioneer Core
item.ud-mod-ud-prec-core-final.description = Reviving pioneers was a bad idea
item.ud-mod-ud-seaweed-bundle.name = Seaweed Bundle
item.ud-mod-ud-seaweed-bundle.description = 1
item.ud-mod-ud-tuberculosis.name = Tuberculosis Ore
item.ud-mod-ud-tuberculosis.description = 1
item.ud-mod-ud-iron.name = Iron
item.ud-mod-ud-iron.description = 1
item.ud-mod-ud-silica-sand.name = Silica Sand
item.ud-mod-ud-silica-sand.description = 1
item.ud-mod-ud-manganese.name = Manganese
item.ud-mod-ud-manganese.description = 1
item.ud-mod-ud-aurum.name = Aurum
item.ud-mod-ud-aurum.description = 1
item.ud-mod-ud-nickel.name = Nickel
item.ud-mod-ud-nickel.description = 1
item.ud-mod-ud-francium.name = Francium
item.ud-mod-ud-francium.description = 1
item.ud-mod-ud-chip.name = Basic Chip
item.ud-mod-ud-chip.description = 1
item.ud-mod-ud-manganese-steel.name = Manganese Steel
item.ud-mod-ud-manganese-steel.description = 1
item.ud-mod-ud-pressed-glass.name = Pressed Glass
item.ud-mod-ud-pressed-glass.description = 1
item.ud-mod-ud-advanced-chip.name = Advanced Chip
item.ud-mod-ud-advanced-chip.description = 1
item.ud-mod-ud-shield-alloy.name = Shield Alloy
item.ud-mod-ud-shield-alloy.description = 1
item.ud-mod-ud-rlyeh-alloy.name = R'lyeh Alloy
item.ud-mod-ud-rlyeh-alloy.description = 1
item.ud-mod-ud-gunpowder-chip.name = Gunpowder Chip
item.ud-mod-ud-gunpowder-chip.description = 1
item.ud-mod-ud-gunpowder-manganese-steel.name = Gunpowder Manganese Steel
item.ud-mod-ud-gunpowder-manganese-steel.description = 1
item.ud-mod-ud-gunpowder-advanced-chip.name = Gunpowder Advanced Chip
item.ud-mod-ud-gunpowder-advanced-chip.description = 1
item.ud-mod-ud-gunpowder-shield-alloy.name = Gunpowder Shield Alloy
item.ud-mod-ud-gunpowder-shield-alloy.description = 1
item.ud-mod-ud-gunpowder-francium.name = Gunpowder Francium
item.ud-mod-ud-gunpowder-francium.description = 1
item.ud-mod-ud-gunpowder-rlyeh-alloy.name = Gunpowder R'lyeh Alloy
item.ud-mod-ud-gunpowder-rlyeh-alloy.description = 1

block.ud-mod-ud-depressurization-basic.name = Basic Depressurizer
block.ud-mod-ud-depressurization-basic.description = 1
block.ud-mod-ud-depressurization-advanced.name = Advanced Depressurizer
block.ud-mod-ud-depressurization-advanced.description = 1
block.ud-mod-ud-depressurization-ultimate.name = Ultimate Depressurizer
block.ud-mod-ud-depressurization-ultimate.description = 1
block.ud-mod-ud-infection-launcher.name = Infection Launcher
block.ud-mod-ud-infection-launcher.description = 1
block.ud-mod-ud-gunpowder-factory.name = Gunpowder Factory
block.ud-mod-ud-gunpowder-factory.description = 1
block.ud-mod-ud-prec-core-factory.name = Prec-Core Research Station
block.ud-mod-ud-prec-core-factory.description = 1
block.ud-mod-ud-dri-hydraulic.name = Hydraulic Drill
block.ud-mod-ud-dri-hydraulic.description = 1
block.ud-mod-ud-dri-electrical.name = Electrical Drill
block.ud-mod-ud-dri-electrical.description = 1
block.ud-mod-ud-dri-precise.name = Precise Drill
block.ud-mod-ud-dri-precise.description = 1
block.ud-mod-ud-fac-Ionization.name =电离机
block.ud-mod-ud-fac-Ionization.description = 1
block.ud-mod-ud-fac-sorter.name = Fac Sorter
block.ud-mod-ud-fac-sorter.description = 1
block.ud-mod-ud-fac-etching.name = Fac Etching
block.ud-mod-ud-fac-etching.description = 1
block.ud-mod-ud-fac-compressor.name = Fac Compressor
block.ud-mod-ud-fac-compressor.description = 1
block.ud-mod-ud-fac-fermentation-tank.name = Fac Fermentation Tank
block.ud-mod-ud-fac-fermentation-tank.description = 1
block.ud-mod-ud-fac-glass-kiln.name = Fac Glass Kiln
block.ud-mod-ud-fac-glass-kiln.description = 1
block.ud-mod-ud-fac-advanced-etching.name = Advanced Etching
block.ud-mod-ud-fac-advanced-etching.description = 1
block.ud-mod-ud-fac-charger.name = Charger
block.ud-mod-ud-fac-charger.description = 1
block.ud-mod-ud-fac-incubator.name = Incubator
block.ud-mod-ud-fac-incubator.description = 1
block.ud-mod-ud-fac-bioreactor.name = Bioreactor
block.ud-mod-ud-fac-bioreactor.description = 1
block.ud-mod-ud-fac-halogenator.name = Halogenator
block.ud-mod-ud-fac-halogenator.description = 1
block.ud-mod-ud-fac-rlyeh-foundry.name = R'lyeh Foundry
block.ud-mod-ud-fac-rlyeh-foundry.description = 1
block.ud-mod-ud-advanced-core-factory.name = Advanced Core Research Station
block.ud-mod-ud-advanced-core-factory.description = 1

liquid.ud-mod-ud-fresh-water.name = Fresh Water
liquid.ud-mod-ud-fresh-water.description = 1
liquid.ud-mod-ud-seaweed-oil.name = Seaweed Oil
liquid.ud-mod-ud-seaweed-oil.description = 1
liquid.ud-mod-ud-root-gel.name = Root Gel
liquid.ud-mod-ud-root-gel.description = 1
liquid.ud-mod-ud-atomic-halogen.name = Atomic Halogen
liquid.ud-mod-ud-atomic-halogen.description = 1
