item.ud-mod-ud-wreckage-alloy.name = Wreckage Alloy
item.ud-mod-ud-wreckage-alloy.description = Pioneer alloy wreckage
item.ud-mod-ud-wreckage-glass.name = Wreckage Glass
item.ud-mod-ud-wreckage-glass.description = Pioneer glass wreckage
item.ud-mod-ud-wreckage-fiber.name = Wreckage Fiber
item.ud-mod-ud-wreckage-fiber.description = Pioneer fiber wreckage
item.ud-mod-ud-root.name = Root
item.ud-mod-ud-root.description = Unknown organic root
item.ud-mod-ud-prec-core-fight.name = Prec-Core: Fight
item.ud-mod-ud-prec-core-fight.description = At least it doesn't bite
item.ud-mod-ud-prec-core-exist.name = Prec-Core: Exist
item.ud-mod-ud-prec-core-exist.description = Why won't it come apart
item.ud-mod-ud-prec-core-migrate.name = Prec-Core: Migrate
item.ud-mod-ud-prec-core-migrate.description = Probe misaligned again
item.ud-mod-ud-prec-core-final.name = Pioneer Core
item.ud-mod-ud-prec-core-final.description = Reviving pioneers was a bad idea
item.ud-mod-ud-seaweed-bundle.name = Seaweed Bundle
item.ud-mod-ud-seaweed-bundle.description = 1
item.ud-mod-ud-tuberculosis.name = Tuberculosis Ore
item.ud-mod-ud-tuberculosis.description = 1
item.ud-mod-ud-iron.name = Iron
item.ud-mod-ud-iron.description = 1
item.ud-mod-ud-silica-sand.name = Silica Sand
item.ud-mod-ud-silica-sand.description = 1
item.ud-mod-ud-manganese.name = Manganese
item.ud-mod-ud-manganese.description = 1
item.ud-mod-ud-aurum.name = Aurum
item.ud-mod-ud-aurum.description = 1
item.ud-mod-ud-nickel.name = Nickel
item.ud-mod-ud-nickel.description = 1
item.ud-mod-ud-francium.name = Francium
item.ud-mod-ud-francium.description = 1
item.ud-mod-ud-chip.name = Basic Chip
item.ud-mod-ud-chip.description = 1
item.ud-mod-ud-manganese-steel.name = Manganese Steel
item.ud-mod-ud-manganese-steel.description = 1
item.ud-mod-ud-pressed-glass.name = Pressed Glass
item.ud-mod-ud-pressed-glass.description = 1
item.ud-mod-ud-advanced-chip.name = Advanced Chip
item.ud-mod-ud-advanced-chip.description = 1
item.ud-mod-ud-shield-alloy.name = Shield Alloy
item.ud-mod-ud-shield-alloy.description = 1
item.ud-mod-ud-rlyeh-alloy.name = R'lyeh Alloy
item.ud-mod-ud-rlyeh-alloy.description = 1
item.ud-mod-ud-gunpowder-chip.name = Gunpowder Chip
item.ud-mod-ud-gunpowder-chip.description = 1
item.ud-mod-ud-gunpowder-manganese-steel.name = Gunpowder Manganese Steel
item.ud-mod-ud-gunpowder-manganese-steel.description = 1
item.ud-mod-ud-gunpowder-advanced-chip.name = Gunpowder Advanced Chip
item.ud-mod-ud-gunpowder-advanced-chip.description = 1
item.ud-mod-ud-gunpowder-shield-alloy.name = Gunpowder Shield Alloy
item.ud-mod-ud-gunpowder-shield-alloy.description = 1
item.ud-mod-ud-gunpowder-francium.name = Gunpowder Francium
item.ud-mod-ud-gunpowder-francium.description = 1
item.ud-mod-ud-gunpowder-rlyeh-alloy.name = Gunpowder R'lyeh Alloy
item.ud-mod-ud-gunpowder-rlyeh-alloy.description = 1

block.ud-mod-ud-depressurization-basic.name = Basic Depressurizer
block.ud-mod-ud-depressurization-basic.description = 1
block.ud-mod-ud-depressurization-advanced.name = Advanced Depressurizer
block.ud-mod-ud-depressurization-advanced.description = 1
block.ud-mod-ud-depressurization-ultimate.name = Ultimate Depressurizer
block.ud-mod-ud-depressurization-ultimate.description = 1
block.ud-mod-ud-infection-launcher.name = Infection Launcher
block.ud-mod-ud-infection-launcher.description = 1
block.ud-mod-ud-prec-core-factory.name = Prec-Core Research Station
block.ud-mod-ud-prec-core-factory.description = 1
block.ud-mod-ud-depth-test-block.name = Depth Efficiency Tester
block.ud-mod-ud-depth-test-block.description = 1

liquid.ud-mod-ud-fresh-water.name = Fresh Water
liquid.ud-mod-ud-fresh-water.description = 1
liquid.ud-mod-ud-seaweed-oil.name = Seaweed Oil
liquid.ud-mod-ud-seaweed-oil.description = 1
liquid.ud-mod-ud-root-gel.name = Root Gel
liquid.ud-mod-ud-root-gel.description = 1
liquid.ud-mod-ud-atomic-halogen.name = Atomic Halogen
liquid.ud-mod-ud-atomic-halogen.description = 1
